#   _____ ____  __  __ __  __ _____ _______ _____ ____________ _   _ 
#  / ____/ __ \|  \/  |  \/  |_   _|__   __|_   _|___  /  ____| \ | |
# | |   | |  | | \  / | \  / | | |    | |    | |    / /| |__  |  \| |
# | |   | |  | | |\/| | |\/| | | |    | |    | |   / / |  __| | . ` |
# | |___| |__| | |  | | |  | |_| |_   | |   _| |_ / /__| |____| |\  |
#  \_____\____/|_|  |_|_|  |_|_____|  |_|  |_____/_____|______|_| \_|
# https://commitizen-tools.github.io/commitizen/

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.1.0"
update_changelog_on_bump = true
major_version_zero = true
