# https://starship.rs/                                                        

# General settings
add_newline = false
format = """
$username\
$hostname\
$python\
$conda\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$character"""

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "blue"
truncate_to_repo = true
format = "[$path]($style) "

[git_branch]
format = "[$branch]($style) "
style = "purple"
disabled = false

[git_status]
format = "$ahead_behind$staged$modified$renamed$deleted$stashed$untracked"
conflicted = "[!${count} ](bright-red)"
ahead = "[ ${count} ](bright-blue)"
behind = "[ ${count} ](bright-blue)"
# diverged = "[ ${ahead_count}: ${behind_count} ](bright-blue)"
untracked = "[?${count} ](red)"
stashed = "[*${count} ](black)"
modified = "[~${count} ](yellow)"
staged = "[+${count} ](green)"
renamed = "[~${count} ](yellow)"
deleted = "[~${count} ](yellow)"

[cmd_duration]
min_time = 0
format = "[$duration]($style) "
style = "bright-purple"
show_milliseconds = true

[jobs]
symbol = "✦ "
style = "bright-blue"

[battery]
disabled = true

[time]
format = ""
disabled = true

[character]
success_symbol = "[](white)"
error_symbol = "[](bright-red)"
vicmd_symbol = "[](yellow)"

[python]
symbol = ' '  # Ensure single quotes around the symbol
format = '[$symbol$virtualenv]($style) '
style = "yellow"
python_binary = ["python", "python3", "python2"]
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", "setup.py", "Pipfile"]
detect_folders = [".venv", "venv"]
