add_newline = false
format = "$username$conda$directory$git_branch$git_commit$git_state$git_metrics$git_status$status$character"
palette = "sourdiesel"
right_format = "$lua$python"

[character]
success_symbol = '[>](white)'
error_symbol = '[>](red)'

[conda]
style = 'green'
format = '[$environment]($style) '
ignore_base = false

[directory]
truncation_length = 1
# format = ''
style = 'magenta'

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'blue'

[git_commit]
format = '[$hash$tag]($style) '
style = 'yellow'

[git_state]
style = 'yellow'
format = '[$state $progress_current/$progress_total]($style) '

[git_status]
format = '[$all_status$ahead_behind]($style)'
conflicted  = '=${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
untracked = '?${count} '
stashed = '$${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '✘${count} '
style = 'text'

[lua]
format = '[$symbol($version )]($style) '
symbol = 'lua '
style = 'bright-blue'

[palettes.sourdiesel]
black = "#CCCCCC"
red = "#FFC7C7"
green = "#CEFFC9"
yellow = "#FDF7CD"
blue = "#C4EFFA"
magenta = "#ECCEF0"
cyan = "#94e2d5"
white = "#F4F3F2"
bright-black = "#5C617D"
bright-red = "#F096B7"
bright-green = "##D2FD9D"
bright-yellow = "#F3B175"
bright-blue= "#80D7FE"
bight-magenta = "#C9CCFB"
bright-cyan = "#47E7B1"
bright-white = "#FFFFFF"
text = "#C9CCFB"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#5c617d"
mantle = "#181825"
crust = "#11111b"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )($virtualenv )]($style)'
symbol = 'python '
style = 'green'

[status]
format = '[$status]($style) '
style = 'bright-red'
disabled = false

[username]
style_root = 'red'
style_user = 'yellow'
format = '[$user]($style) '

