# https://wezfurlong.org/wezterm/config/appearance.html#defining-a-color-scheme-in-your-weztermlua

[colors]
ansi = [
  "#cccccc", # black
  "#ffc7c7", # red
  "#ceffc9", # green
  "#fdf7cd", # yellow
  "#c4effa", # blue
  "#eccef0", # magenta
  "#8ae7c5", # cyan
  "#f4f3f2", # white
]

background = "#212030"

brights = [
  "#5c617d", # bright black
  "#f096b7", # bright red
  "#d2fd9d", # bright green
  "#f3b175", # bright yellow
  "#80d7fe", # bright blue
  "#c9ccfb", # bright magenta
  "#47e7b1", # bright cyan
  "#ffffff", # bright white
]

compose_cursor = '#f2cdcd'
cursor_bg = "#cdd6f4"
cursor_border = "#f4f3f2"
cursor_fg = "#313244"

foreground = "#f4f3f2"
selection_bg = "#5c617d"
selection_fg = "#f4f3f2"
split = '#5c617d'

[metadata]
aliases = []
author = 'Vivek Jha'
name = 'Sourdiesel'
